# Set the latest golang base image:
FROM golang:latest

# Set the Current Working Directory inside the container
WORKDIR /app

# Build server:
COPY  ./ ./
RUN go mod download
RUN go build -o app .

# Expose server port:
EXPOSE 7000

# App version (uncomment if the image is for non-development ends):
# ENV APP_VERSION "YOUR_VERSION"

# Run the server:
CMD ["./app"]